pipeline {
    agent any
    stages {
        stage("Clear") {
            steps{
                deleteDir()
            }
        }
        stage("Run Server"){

         steps {
          sh "ls"
          sh "pwd"
          dir("TourAndTravel-React-Node/server") {
          sh "npm i"
          sh "npm start"

          }

         }
        }
        stage("Run Client"){
         steps {
          dir("TourAndTravel-React-Node/client") {
          sh "npm i"
          sh "npm run dev"

          }

         }
        }
    }
}